# Generated by Django 3.0.5 on 2020-04-29 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('options', models.ManyToManyField(to='web.Option')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='next_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Place'),
        ),
    ]
