# Generated by Django 3.0.5 on 2020-04-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
